
server:
  port: 8082
#  max-http-header-size: 10MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cntt_master_qlbh2022
    username: root
    password: 123456789

    #Connection pool
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      tomcat.max-idle: 15
      min-idle: 8
      default-auto-commit: true

  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: update
#      ddl-auto: create-drop

#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL55Dialect

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB

  main:
    allow-circular-references: true

logging:
  level:
    com:
      project:
        quanlybanhang: DEBUG

